name: Android Lint

on:
  pull_request:
    branches:
      - main # or specify your desired branch

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run lint
        run: ./gradlew lint
