name: Android Lint

on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [ opened, edited, synchronize, reopened ]
    branches-ignore: [ production ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          clean: true

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Set execute permissions
        run: chmod +x gradlew

      - name: Run lint
        run: bash ./gradlew lintDebug

      -name: Upload html test report
       uses: actions/upload-artifact@v2
       with:
         name: index.html
         path: app/build/reports/lint-results-debug.html
