name: Lint Check

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'

      - name: Build and Test
        run: |
          ./gradlew assembleDebug
          ./gradlew testDebug

      - name: Run Lint Check
        run: ./gradlew lint
